### ISSUE TITLE
Confusing JSX syntax for terminating an input tag

### ISSUE THREAD

**Issue by joshuabamboo** [learn-co-curriculum/react-jsx-lab#3]
It may be worth noting the syntax for closing html `input` tags in JSX.
For example:
`class SomeClass extends React.Component{
  render(){
    return (
      <form>
        <input type='text'>
      </form>
    );
  }
}`

This code will give you an `Unterminated JSX contents` error when running `npm run bundle` because the `input` does not have the `/` (ie `<input type='text'/>`). 

[React doc that shows this](https://facebook.github.io/react/docs/forms.html)

**Comment by gj** [comment]
Fixed here: https://github.com/learn-co-curriculum/react-jsx-lab/pull/9

Thanks @joshuabamboo !
