### ISSUE TITLE
Export error

### ISSUE THREAD

**Issue by Traci7822** [learn-co-curriculum/react-jsx-lab#5]
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in.
/Users/traci/code/react-jsx-lab-learn-experts-testing-batch/node_modules/react-dom/lib/ReactCompositeComponent.js:306
        return Component(publicProps, publicContext, updateQueue);
               ^

TypeError: Component is not a function
    at /Users/traci/code/react-jsx-lab-learn-experts-testing-batch/node_modules/react-dom/lib/ReactCompositeComponent.js:306:16

**Comment by Traci7822** [comment]
@aturkewi 
This is the issue we spoke about. In this lab running 'npm run bundle' does not fix it so the html page still has load errors:

`Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in.
printWarning @ bundle.js:13774
warning @ bundle.js:13798
createElement @ bundle.js:57533
4../components/RegistrationForm @ bundle.js:22
s @ bundle.js:1
e @ bundle.js:1
(anonymous) @ bundle.js:1
bundle.js:13774 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in.
printWarning @ bundle.js:13774
warning @ bundle.js:13798
createElement @ bundle.js:57533
4../components/RegistrationForm @ bundle.js:23
s @ bundle.js:1
e @ bundle.js:1
(anonymous) @ bundle.js:1
bundle.js:13521 Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in.
    at invariant (bundle.js:13521)
    at instantiateReactComponent (bundle.js:54349)
    at instantiateChild (bundle.js:42895)
    at bundle.js:42922
    at traverseAllChildrenImpl (bundle.js:54863)
    at traverseAllChildrenImpl (bundle.js:54879)
    at traverseAllChildren (bundle.js:54958)
    at Object.instantiateChildren (bundle.js:42921)
    at ReactDOMComponent._reconcilerInstantiateChildren (bundle.js:49041)
    at ReactDOMComponent.mountChildren (bundle.js:49080)`

**Comment by aturkewi** [comment]
@JeffKatzy 
I think just before this lab (or maybe _in_ this lab) we want to talk about this error and what it is. Thoughts?

**Comment by jawadbanga** [comment]
Yeah having same problem in all of the React labs?

**Comment by jawadbanga** [comment]
Ok I got it. Make sure you are getting all your requires and exports. There might be a component on another file you are referencing to so make sure you require that file containing the component. Cheers

**Comment by jawadbanga** [comment]
I think it will be useful to go over common errors in an early react lesson.

**Comment by gj** [comment]
Fixed here: https://github.com/learn-co-curriculum/react-jsx-lab/pull/9

Thanks @Traci7822 !
